name: Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: black
      run: |
        black --check custom_components
    - name: isort
      run: |
        isort --check custom_components
    - name: pylint
      run: |
        pylint custom_components
    - name: mypy
      run: |
        mypy custom_components
